version: '3'

services:
  db:
    container_name: 'postgres'
    image: 'postgres:15'
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

  bot:
    container_name: 'bot'
    image: 'go-bot'
    restart: always
    environment:
      TOKEN: ${TOKEN}
      URL: http://host.docker.internal:${SERVER_PORT}/requests

  server:
    container_name: 'server'
    image: 'go-server'
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: ${POSTGRES_PORT}
      SERVER_PORT: ${SERVER_PORT}
    volumes:
      - './db-data:/var/lib/postgresql/data'
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
